// mutation-types
export const updateCount = 'updateCount'
export const fillTodos = 'fillTodos'
export const addTodo = 'addTodo'
export const updateTodo = 'updateTodo'
export const deleteTodo = 'deleteTodo'
export const deleteAllCompleted = 'deleteAllCompleted'
export const doLogin = 'doLogin'
export const startLoading = 'startLoading'
export const endLoading = 'endLoading'
